require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/inventories', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Inventory. As you add validations to Inventory, be sure to
  # adjust the attributes here as well.
  let(:user) { create(:user) }
  let(:inventory) { create(:inventory, user: user) }

  before do
    sign_in user
  end

  describe 'GET /inventories' do
    it 'renders the index template' do
      get inventories_path
      expect(response).to render_template(:index)
    end

    # Add more tests as needed
  end

  describe 'GET /inventories/:id' do
    it 'renders the show template' do
      get inventory_path(inventory)
      expect(response).to render_template(:show)
    end

    # Add more tests as needed
  end

  describe 'GET /inventories/new' do
    it 'renders the new template' do
      get new_inventory_path
      expect(response).to render_template(:new)
    end

    # Add more tests as needed
  end

  describe 'POST /inventories' do
    context 'with valid parameters' do
      it 'creates a new inventory' do
        expect do
          post inventories_path, params: { inventory: attributes_for(:inventory) }
        end.to change(Inventory, :count).by(1)
      end

      it 'redirects to the created inventory' do
        post inventories_path, params: { inventory: attributes_for(:inventory) }
        expect(response).to redirect_to(inventory_path(Inventory.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new inventory' do
        expect do
          post inventories_path, params: { inventory: { name: nil } }
        end.to_not change(Inventory, :count)
      end

      it 'renders the new template' do
        post inventories_path, params: { inventory: { name: nil } }
        expect(response).to render_template(:new)
      end
    end
  end

  describe 'DELETE /inventories/:id' do
    it 'destroys the requested inventory' do
      inventory_to_destroy = create(:inventory, user:)
      expect do
        delete inventory_path(inventory_to_destroy)
      end.to change(Inventory, :count).by(-1)
    end

    it 'redirects to the inventories list' do
      delete inventory_path(inventory)
      expect(response).to redirect_to(inventories_path)
    end
  end

  # describe 'GET /new' do
  #   it 'renders a successful response' do
  #     get new_inventory_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe 'GET /edit' do
  #   it 'renders a successful response' do
  #     inventory = Inventory.create! valid_attributes
  #     get edit_inventory_url(inventory)
  #     expect(response).to be_successful
  #   end
  # end

  # describe 'POST /create' do
  #   context 'with valid parameters' do
  #     it 'creates a new Inventory' do
  #       expect do
  #         post inventories_url, params: { inventory: valid_attributes }
  #       end.to change(Inventory, :count).by(1)
  #     end

  #     it 'redirects to the created inventory' do
  #       post inventories_url, params: { inventory: valid_attributes }
  #       expect(response).to redirect_to(inventory_url(Inventory.last))
  #     end
  #   end

  #   context 'with invalid parameters' do
  #     it 'does not create a new Inventory' do
  #       expect do
  #         post inventories_url, params: { inventory: invalid_attributes }
  #       end.to change(Inventory, :count).by(0)
  #     end

  #     it "renders a response with 422 status (i.e. to display the 'new' template)" do
  #       post inventories_url, params: { inventory: invalid_attributes }
  #       expect(response).to have_http_status(:unprocessable_entity)
  #     end
  #   end
  # end

  # describe 'PATCH /update' do
  #   context 'with valid parameters' do
  #     let(:new_attributes) do
  #       skip('Add a hash of attributes valid for your model')
  #     end

  #     it 'updates the requested inventory' do
  #       inventory = Inventory.create! valid_attributes
  #       patch inventory_url(inventory), params: { inventory: new_attributes }
  #       inventory.reload
  #       skip('Add assertions for updated state')
  #     end

  #     it 'redirects to the inventory' do
  #       inventory = Inventory.create! valid_attributes
  #       patch inventory_url(inventory), params: { inventory: new_attributes }
  #       inventory.reload
  #       expect(response).to redirect_to(inventory_url(inventory))
  #     end
  #   end

  #   context 'with invalid parameters' do
  #     it "renders a response with 422 status (i.e. to display the 'edit' template)" do
  #       inventory = Inventory.create! valid_attributes
  #       patch inventory_url(inventory), params: { inventory: invalid_attributes }
  #       expect(response).to have_http_status(:unprocessable_entity)
  #     end
  #   end
  # end

  # describe 'DELETE /destroy' do
  #   it 'destroys the requested inventory' do
  #     inventory = Inventory.create! valid_attributes
  #     expect do
  #       delete inventory_url(inventory)
  #     end.to change(Inventory, :count).by(-1)
  #   end

  #   it 'redirects to the inventories list' do
  #     inventory = Inventory.create! valid_attributes
  #     delete inventory_url(inventory)
  #     expect(response).to redirect_to(inventories_url)
  #   end
  # end
end
